image: "java:8-jdk"

maven-test: 
  image: "maven:3-jdk-8"
  script: "mvn test"
  stage: test
  
maven-build: 
  image: "maven:3-jdk-8"
  script: "mvn package -DskipTests"
  stage: build

stages: 
  - test
  - build
